language: python
python:
  - "3.9"
  - "3.8"

install:
  - pip install pipenv
  - pipenv install --system --dev
  - pip install coveralls flake8 mypy
  - pip install .

script:
  - flake8 deebot
  - black --check deebot
  - mypy --strict nsw_fuel

after_success: coveralls

before_deploy:
  - git describe --tags > VERSION

deploy:
  provider: pypi
  skip_cleanup: true
  user: nickw444-deploy
  password: "$PYPI_PASSWORD"
  on:
    tags: true
    python: 3.8
